---
name: playapp
director_uuid: 1d186757-4ab4-4eba-b3e6-0d73322901b1

release:
  name: play
  version: 0.18-dev

compilation:
  workers: 4
  network: default
  cloud_properties:
    ram: 2048
    disk: 8096
    cpu: 2

# this section describes how updates are handled
update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 4
  max_errors: 1

networks:
  - name: default
    subnets:
    - reserved:
      - 172.16.29.2 - 172.16.29.10
      static:
      - 172.16.29.11 - 172.16.29.100
      range: 172.16.29.0/22
      gateway: 172.16.29.1
      dns:
      - 8.8.8.8
      - 8.4.4.4
      cloud_properties:
        name: VM Network
  
resource_pools:
  - name: infrastructure
    network: default
    size: 6
    stemcell:
      name: bosh-stemcell
      version: 0.8.0
    cloud_properties:
      cpu: 1
      disk: 8192
      ram: 4096

jobs:
  # - name: mysql
  #   template: mysql
  #   instances: 1
  #   resource_pool: infrastructure
  #   persistent_disk: 16384
  #   networks:
  #   - name: default
  #     static_ips:
  #     - 172.16.29.20

  - name: play
    template: playapp
    instances: 1
    resource_pool: infrastructure
    networks:
    - name: default
      static_ips:
      - 172.16.29.30 # - 172.16.29.33

  - name: nginx
    template: nginx
    instances: 1
    resource_pool: infrastructure
    networks:
    - name: default
      default: [dns, gateway]
      static_ips:
        - 172.16.29.40 #- 172.32.220.41
    
properties:

  play:
  #   admin: foo@bar.com
     port: 9000
     servers:
       - 172.16.29.30
  #     # - 172.16.29.31
  #     # - 172.16.29.32
  #     # - 172.16.29.33
     servername: playtest.test
  #   db:
  #     name: wp
  #     user: wordpress
  #     pass: w0rdpr3ss

  # mysql:
  #   address: 172.16.29.20
  #   port: 3306
  #   password: rootpass

  nginx:
    workers: 1


