---
name: wordpress
director_uuid: 5960edfe-5cf4-4b70-95fa-728a52f12b56 # CHANGE: Director UUID

release:
  name: wordpress
  version: latest

compilation:
  workers: 3
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.small

update:
  canaries: 1
  canary_watch_time: 3000-120000
  update_watch_time: 3000-120000
  max_in_flight: 4
  max_errors: 1

networks:
  - name: floating
    type: vip
    cloud_properties: {}
  - name: default
    type: dynamic
    cloud_properties:
      security_groups:
      - default # CHANGE: Security Group

resource_pools:
  - name: common
    network: default
    size: 4
    stemcell:
      name: bosh-stemcell
      version: latest
    cloud_properties:
      instance_type: m1.small

jobs:
  - name: mysql
    template: mysql
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]
      - name: floating
        static_ips:
        - 192.168.1.226 # CHANGE: Floating IP 1

  - name: nfs
    template: debian_nfs_server
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]
      - name: floating
        static_ips:
        - 192.168.1.227 # CHANGE: Floating IP 2

  - name: wordpress
    template: wordpress
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]
      - name: floating
        static_ips:
        - 192.168.1.228 # CHANGE: Floating IP 3

  - name: nginx
    template: nginx
    instances: 1
    resource_pool: common
    networks:
      - name: default
        default: [dns, gateway]
      - name: floating
        static_ips:
        - 192.168.1.229 # CHANGE: Floating IP 4

properties:
  env:

  mysql:
    address: 192.168.1.226 # CHANGE: Floating IP 1
    password: rootpass

  nfs_server:
    address: 192.168.1.227 # CHANGE: Floating IP 2
    network: *.wordpress.microbosh
    idmapd_domain: novalocal

  wordpress:
    admin: foo@bar.com
    servers:
      - 192.168.1.228 # CHANGE: Floating IP 3
    servername: 192.168.1.229 # CHANGE: Floating IP 4
    db:
      name: wp
      user: wordpress
      pass: w0rdpr3ss
    auth_key: random key
    secure_auth_key: random key
    logged_in_key: random key
    nonce_key: random key
    auth_salt: random key
    secure_auth_salt: random key
    logged_in_salt: random key
    nonce_salt: random key
