#!/bin/bash

RUN_DIR=/var/vcap/sys/run/play
LOG_DIR=/var/vcap/sys/log/play
PIDFILE=$RUN_DIR/play.pid

case $1 in

  start)
    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR

    echo $$ > $PIDFILE

    exec /var/vcap/packages/playapp/testapp-1.0-SNAPSHOT/start >>$LOG_DIR/play.stdout.log 2>>$LOG_DIR/play.stderr.log
    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    kill $PID
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: play_ctl {start|stop}" ;;
esac
exit 0
